In [1]:
import pandas as pd
import numpy as np

In [2]:
cars_data = pd.read_csv(r'C:\Users\HP\python_datasets\cars.csv', header=None)  

In [3]:
cars_data.head() 

0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

In [4]:
cars_data.shape

(1728, 7)

In [5]:
cars_data.columns = ['buying','maint','doors','persons','lug_boot','safety','classes'] 

In [6]:
cars_data.head() 

buying  maint doors persons lug_boot safety classes
0  vhigh  vhigh     2       2    small    low   unacc
1  vhigh  vhigh     2       2    small    med   unacc
2  vhigh  vhigh     2       2    small   high   unacc
3  vhigh  vhigh     2       2      med    low   unacc
4  vhigh  vhigh     2       2      med    med   unacc

In [7]:
cars_data.isnull().sum() 

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [8]:
cars_df = pd.DataFrame.copy(cars_data) 

In [9]:
colname = cars_df.columns
colname

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'classes'], dtype='object')

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder() 

for x in colname:
    cars_df[x] = le.fit_transform(cars_df[x])  

In [11]:
cars_df.head() 

buying  maint  doors  persons  lug_boot  safety  classes
0       3      3      0        0         2       1        2
1       3      3      0        0         2       2        2
2       3      3      0        0         2       0        2
3       3      3      0        0         1       1        2
4       3      3      0        0         1       2        2

In [12]:
 cars_data['classes'].value_counts() 

unacc    1210
acc       384
good       69
vgood      65
Name: classes, dtype: int64

In [13]:
X = cars_df[['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety']] 
Y = cars_df['classes'] 

In [14]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler() 
scaler.fit(X) 
X = scaler.transform(X) 

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=10) 

# Running Decision Tree model

In [17]:
from sklearn.tree import DecisionTreeClassifier
model_DecisionTree = DecisionTreeClassifier(criterion="gini", random_state=10) 
model_DecisionTree.fit(X_train, y_train) 

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=10, splitter='best')

In [18]:
Y_pred = model_DecisionTree.predict(X_test) 
print(list(zip(y_test, Y_pred))) 

[(2, 2), (2, 2), (2, 2), (2, 2), (1, 1), (2, 2), (0, 0), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (3, 3), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (1, 1), (3, 3), (1, 1), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (3, 3), (2, 2), (2, 2), (0, 0), (0, 0), (2, 2), (2, 2), (3, 3), (2, 2), (2, 2), (2, 2), (1, 1), (2, 2), (0, 0), (3, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (1, 1), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0),

In [19]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, Y_pred)) 
print(classification_report(y_test, Y_pred)) 
print('Accuracy of the model is',accuracy_score(y_test, Y_pred))  

[[101   0   1   0]
 [  2  19   0   0]
 [  0   0 371   0]
 [  1   0   0  24]]
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       102
           1       1.00      0.90      0.95        21
           2       1.00      1.00      1.00       371
           3       1.00      0.96      0.98        25

    accuracy                           0.99       519
   macro avg       0.99      0.96      0.98       519
weighted avg       0.99      0.99      0.99       519

Accuracy of the model is 0.9922928709055877


In [20]:
print(list(zip(cars_df.columns, model_DecisionTree.feature_importances_))) 

[('buying', 0.1510848831946676), ('maint', 0.2506508516803624), ('doors', 0.060026331736828115), ('persons', 0.19355707150872045), ('lug_boot', 0.09892620952419463), ('safety', 0.2457546523552268)]


In [21]:
from sklearn import tree
with open("model_DecisionTree.txt", "w") as f:
    f = tree.export_graphviz(model_DecisionTree, feature_names=cars_df.columns[:-1], out_file=f) 

#generate the file and upload the code in webgraphviz.com to plot the decision tree

# Tuning the decision tree

In [22]:
#this decision tree model does not require tuning as it is giving very good accuracy and not overfitting
#tuning the model just for experiment purpose
model_DecisionTree = DecisionTreeClassifier(criterion="gini", min_samples_leaf=5,
                                            max_depth=10,
                                            random_state=10) 

model_DecisionTree.fit(X_train, y_train)  

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=10,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=5, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=10, splitter='best')

In [23]:
Y_pred = model_DecisionTree.predict(X_test) 

In [24]:
print(confusion_matrix(y_test, Y_pred)) 
print(classification_report(y_test, Y_pred)) 
print('Accuracy of the model is',accuracy_score(y_test, Y_pred))  

[[ 92   6   4   0]
 [  0  17   2   2]
 [  8   0 363   0]
 [  3   5   0  17]]
              precision    recall  f1-score   support

           0       0.89      0.90      0.90       102
           1       0.61      0.81      0.69        21
           2       0.98      0.98      0.98       371
           3       0.89      0.68      0.77        25

    accuracy                           0.94       519
   macro avg       0.84      0.84      0.84       519
weighted avg       0.95      0.94      0.94       519

Accuracy of the model is 0.9421965317919075


# Running ExraTreesClassifier model

In [25]:
from sklearn.ensemble import ExtraTreesClassifier
model = ExtraTreesClassifier(n_estimators=100, random_state=10) 
model = model.fit(X_train, y_train) 
Y_pred = model.predict(X_test) 

In [26]:
print(confusion_matrix(y_test, Y_pred)) 
print(classification_report(y_test, Y_pred)) 
print('Accuracy of the model is',accuracy_score(y_test, Y_pred))  

[[101   1   0   0]
 [  3  18   0   0]
 [  1   0 370   0]
 [  1   2   0  22]]
              precision    recall  f1-score   support

           0       0.95      0.99      0.97       102
           1       0.86      0.86      0.86        21
           2       1.00      1.00      1.00       371
           3       1.00      0.88      0.94        25

    accuracy                           0.98       519
   macro avg       0.95      0.93      0.94       519
weighted avg       0.98      0.98      0.98       519

Accuracy of the model is 0.9845857418111753


# Running Random Forest model

In [27]:
from sklearn.ensemble import RandomForestClassifier
model_RandomForest = RandomForestClassifier(n_estimators=101, max_depth=8) 
model_RandomForest.fit(X_train, y_train) 
Y_pred = model_RandomForest.predict(X_test) 

In [28]:
print(confusion_matrix(y_test, Y_pred)) 
print(classification_report(y_test, Y_pred)) 
print('Accuracy of the model is',accuracy_score(y_test, Y_pred))  

[[ 99   0   3   0]
 [ 13   7   0   1]
 [  2   0 369   0]
 [  1   0   0  24]]
              precision    recall  f1-score   support

           0       0.86      0.97      0.91       102
           1       1.00      0.33      0.50        21
           2       0.99      0.99      0.99       371
           3       0.96      0.96      0.96        25

    accuracy                           0.96       519
   macro avg       0.95      0.81      0.84       519
weighted avg       0.96      0.96      0.96       519

Accuracy of the model is 0.9614643545279383


# Running AdaBoost classifier

In [29]:
from sklearn.ensemble import AdaBoostClassifier

#we can pass any classifier algorithms in the base estimator using AdaBoost
model_AdaBoost = AdaBoostClassifier(base_estimator=DecisionTreeClassifier(random_state=10),
                                   n_estimators=10,
                                   random_state=10) 

model_AdaBoost.fit(X_train, y_train) 
Y_pred = model_AdaBoost.predict(X_test) 

In [30]:
print(confusion_matrix(y_test, Y_pred)) 
print(classification_report(y_test, Y_pred)) 
print('Accuracy of the model is',accuracy_score(y_test, Y_pred))  

[[ 99   2   1   0]
 [  4  17   0   0]
 [  0   0 371   0]
 [  1   0   0  24]]
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       102
           1       0.89      0.81      0.85        21
           2       1.00      1.00      1.00       371
           3       1.00      0.96      0.98        25

    accuracy                           0.98       519
   macro avg       0.96      0.94      0.95       519
weighted avg       0.98      0.98      0.98       519

Accuracy of the model is 0.9845857418111753


# Running Gradient Boosting Classifier

In [31]:
from sklearn.ensemble import GradientBoostingClassifier

#Gradient Boosting can only use decision tree for classification
model_GradientBoosting = GradientBoostingClassifier(n_estimators=150, random_state=10) 
model_GradientBoosting.fit(X_train, y_train) 
Y_pred = model_GradientBoosting.predict(X_test) 

In [32]:
print(confusion_matrix(y_test, Y_pred)) 
print(classification_report(y_test, Y_pred)) 
print('Accuracy of the model is',accuracy_score(y_test, Y_pred))  

[[101   1   0   0]
 [  0  21   0   0]
 [  0   0 371   0]
 [  0   0   0  25]]
              precision    recall  f1-score   support

           0       1.00      0.99      1.00       102
           1       0.95      1.00      0.98        21
           2       1.00      1.00      1.00       371
           3       1.00      1.00      1.00        25

    accuracy                           1.00       519
   macro avg       0.99      1.00      0.99       519
weighted avg       1.00      1.00      1.00       519

Accuracy of the model is 0.9980732177263969


In [33]:
from xgboost import XGBClassifier

#xgb also uses decision tree for classification
model_xgb = XGBClassifier(random_state=10) 
model_xgb.fit(X_train, y_train) 
Y_pred = model_xgb.predict(X_test) 

In [34]:
print(confusion_matrix(y_test, Y_pred)) 
print(classification_report(y_test, Y_pred)) 
print('Accuracy of the model is',accuracy_score(y_test, Y_pred))  

[[ 97   3   2   0]
 [  7  10   0   4]
 [  3   1 367   0]
 [  0   0   0  25]]
              precision    recall  f1-score   support

           0       0.91      0.95      0.93       102
           1       0.71      0.48      0.57        21
           2       0.99      0.99      0.99       371
           3       0.86      1.00      0.93        25

    accuracy                           0.96       519
   macro avg       0.87      0.85      0.85       519
weighted avg       0.96      0.96      0.96       519

Accuracy of the model is 0.9614643545279383


In [38]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier

#create the sub models
estimators = [] 
model1 = LogisticRegression() 
estimators.append(('log',model1)) 
model2 = DecisionTreeClassifier(criterion="gini", random_state=10)
estimators.append(('cart', model2)) 
model3 = SVC(kernel='rbf', C=50, gamma=0.1) 
estimators.append(('svm', model3)) 
model4 = KNeighborsClassifier(n_neighbors=8, metric='euclidean') 
estimators.append(('knn', model4)) 

#create the ensemble model
ensemble = VotingClassifier(estimators) 
ensemble.fit(X_train, y_train) 
Y_pred = ensemble.predict(X_test) 

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [39]:
print(confusion_matrix(y_test, Y_pred)) 
print(classification_report(y_test, Y_pred)) 
print('Accuracy of the model is',accuracy_score(y_test, Y_pred))  

[[101   1   0   0]
 [  4  17   0   0]
 [  2   0 369   0]
 [  2   0   0  23]]
              precision    recall  f1-score   support

           0       0.93      0.99      0.96       102
           1       0.94      0.81      0.87        21
           2       1.00      0.99      1.00       371
           3       1.00      0.92      0.96        25

    accuracy                           0.98       519
   macro avg       0.97      0.93      0.95       519
weighted avg       0.98      0.98      0.98       519

Accuracy of the model is 0.9826589595375722
